In [62]:
from extract import request_openlibrary
import pandas as pd

In [63]:
raw_data = request_openlibrary("subjects", "cinema")
df_raw = pd.DataFrame(raw_data.get("works", []))

Dados extraídos com sucesso!

### Transform/Clean

In [ ]:
print(f"Quantidade de registros:{len(df_raw)}")
print(f"Quantidade de colunas:{len(df_raw.columns)}")
df_raw.info()
df_raw

Quantidade de registros:12
Quantidade de colunas:16
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   key                 12 non-null     str
 1   title               12 non-null     str
 2   edition_count       12 non-null     int64
 3   cover_id            11 non-null     float64
 4   cover_edition_key   9 non-null      str
 5   subject             12 non-null     object
 6   ia_collection       12 non-null     object
 7   printdisabled       12 non-null     bool
 8   lending_edition     12 non-null     str
 9   lending_identifier  12 non-null     str
 10  authors             12 non-null     object
 11  first_publish_year  12 non-null     int64
 12  ia                  10 non-null     str
 13  public_scan         12 non-null     bool
 14  has_fulltext        12 non-null     bool
 15  availability        10 non-null     object
dtypes: bool(3), float64(1), int64(2), object(4), str(6)
memory usage: 1.4+ KB

,key,title,edition_count,cover_id,cover_edition_key,subject,ia_collection,printdisabled,lending_edition,lending_identifier,authors,first_publish_year,ia,public_scan,has_fulltext,availability
0,/works/OL15719630W,Divergent,87,13274634.0,OL26223598M,"[New York Times bestseller, nyt:paperback_book...","[delawarecountydistrictlibrary-ol, georgetown-...",True,OL47748336M,1divergent0000vero,"[{'key': '/authors/OL6895646A', 'name': 'Veron...",2010,1divergent0000vero,False,True,"{'status': 'borrow_available', 'available_to_b..."
1,/works/OL8101202W,Film Studies,24,1218567.0,OL7493068M,"[Motion pictures, Film criticism, Motion pictu...","[dartmouthlibrary-ol, gwulibraries-ol, interne...",True,,,"[{'key': '/authors/OL2698167A', 'name': 'Amy V...",2006,filmstudies0000vill,False,True,"{'status': 'private', 'available_to_browse': F..."
2,/works/OL2030265W,Tacita Dean,19,2249492.0,OL8987267M,"[Cinematography, Abstract, Performance art, Ex...",[],False,,,"[{'key': '/authors/OL245385A', 'name': 'Tacita...",1998,NaN,False,False,NaN
3,/works/OL550723W,Understanding movies,18,88910.0,NaN,"[Motion pictures, Textbooks, Aesthetics, Analy...","[internetarchivebooks, printdisabled]",True,,,"[{'key': '/authors/OL39207A', 'name': 'Louis D...",1972,understandingmov00gian_1,False,True,"{'status': 'private', 'available_to_browse': F..."
4,/works/OL1632964W,Kitsch,16,7283834.0,NaN,"[architecture, art, camp, bio-pics, design, fi...","[inlibrary, internetarchivebooks, printdisabled]",True,OL4753714M,kitschworldofbad0000dorf,"[{'key': '/authors/OL181580A', 'name': 'Gillo ...",1969,kitschworldofbad0000dorf,False,True,"{'status': 'borrow_available', 'available_to_b..."
5,/works/OL5745510W,Lucky man,15,227135.0,OL3952636M,"[Parkinson's Disease, Biographies, Parkinsonie...","[americana, delawarecountydistrictlibrary, int...",True,,,"[{'key': '/authors/OL1397529A', 'name': 'Micha...",1998,luckyman00mich,False,True,"{'status': 'private', 'available_to_browse': F..."
6,/works/OL4031817W,Looking for Alibrandi,13,658487.0,OL6893861M,"[Juvenile fiction, Catholic schools, Fiction, ...","[internetarchivebooks, printdisabled]",True,,,"[{'key': '/authors/OL747137A', 'name': 'Melina...",1992,lookingforalibra0000marc,False,True,"{'status': 'private', 'available_to_browse': F..."
7,/works/OL3295091W,British national cinema,12,4968848.0,OL9368124M,"[History, Motion pictures, Motion picture indu...","[internetarchivebooks, printdisabled]",True,,,"[{'key': '/authors/OL538969A', 'name': 'Sarah ...",1997,britishnationalc0000stre,False,True,"{'status': 'private', 'available_to_browse': F..."
8,/works/OL18257790W,Psychoanalysis & cinema,9,1221176.0,OL2188158M,"[Psychoanalysis and motion pictures, Psychoana...","[binghamton-ol, dartmouthlibrary-ol, drakeuniv...",True,,,"[{'key': '/authors/OL537805A', 'name': 'E. Ann...",1990,psychoanalysisci0000unse,False,True,"{'status': 'private', 'available_to_browse': F..."
9,/works/OL1644934W,Producing Videos,9,2071096.0,OL8648468M,"[Production and direction, Video recordings, V...",[],False,,,"[{'key': '/authors/OL183510A', 'name': 'Martha...",1997,producingvideosc00moll,False,False,"{'status': 'error', 'error_message': 'not foun..."
10,/works/OL15837167W,I'll Cry Tomorrow,9,6724290.0,OL14575908M,"[Lillian Roth, 1910-1980, Mike Connolly, Gerol...","[inlibrary, internetarchivebooks, printdisabled]",True,OL14575908M,illcrytomorrow00roth,"[{'key': '/authors/OL1662200A', 'name': 'Lilli...",1954,illcrytomorrow00roth,False,True,"{'status': 'borrow_available', 'available_to_b..."
11,/works/OL5278932W,The decline of the cinema,9,NaN,NaN,"[Motion picture industry, Motion picture theat...",[],False,,,"[{'key': '/authors/OL1195293A', 'name': 'John ...",1962,NaN,False,False,NaN

In [ ]:
#Filtrando colunas
cols = ['key', 'title', 'first_publish_year', 'edition_count', 'authors']
df = df_raw[cols]

#Filtrando nome real do autor e dropando tabela antiga
df['author_name'] = df['authors'].apply(lambda x: x[0]['name'] if isinstance(x, list) and len(x) > 0 else None)
df = df.drop(columns=["authors"])

#Limpando a key
df['key'] = df['key'].str.replace('/works/', '', regex=False)

In [73]:
df

,key,title,first_publish_year,edition_count,author_name
0,OL15719630W,Divergent,2010,87,Veronica Roth
1,OL8101202W,Film Studies,2006,24,Amy Villarejo
2,OL2030265W,Tacita Dean,1998,19,Tacita Dean
3,OL550723W,Understanding movies,1972,18,Louis D. Giannetti
4,OL1632964W,Kitsch,1969,16,Gillo Dorfles
5,OL5745510W,Lucky man,1998,15,Michael J. Fox
6,OL4031817W,Looking for Alibrandi,1992,13,Melina Marchetta
7,OL3295091W,British national cinema,1997,12,Sarah Street
8,OL18257790W,Psychoanalysis & cinema,1990,9,E. Ann Kaplan
9,OL1644934W,Producing Videos,1997,9,Martha Mollison
10,OL15837167W,I'll Cry Tomorrow,1954,9,Lillian Roth
11,OL5278932W,The decline of the cinema,1962,9,John Spraos